Correct pyproject.toml to include the AEW API as a dependency.
ansys/pymodelcenter pull request #193
Opened 2024-03-25 14:47 UTC by phx-mkoninckx

2024-03-25 15:10 UTC, clatapie requested changes
Using a specific `ansys-engineeringworkflow-api` version for tests and documentation build helps to ensure that a new package release of the latter doesn't cause any damage within `pymodelcenter` package.

2024-03-25 15:10 UTC, clatapie commented on pyproject.toml
>  doc=[
```suggestion
doc=[
    "ansys-engineeringworkflow-api==0.1.0",
```

2024-03-25 15:10 UTC, clatapie commented on pyproject.toml
>  tests = [
```suggestion
tests = [
    "ansys-engineeringworkflow-api==0.1.0",
```

2024-03-25 18:27 UTC, phx-mpascale approved these changes

2024-03-26 13:44 UTC, clatapie approved these changes
LGTM!

2024-03-26 14:23 UTC, merged